version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bm-service-server
    volumes:
      - sqlite_data:/var/www/database
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: reverb
      REVERB_PORT: 6001
      REVERB_SCHEME: https
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - reverb
    networks:
      - laravel

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bm-service-reverb
    command: ["php", "/var/www/artisan", "reverb:start", "--host=0.0.0.0", "--port=6001", "--debug"]
    stop_signal: SIGTERM
    ports:
      - "6001:6001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  sqlite_data:
