version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:CC4W4w+ETyR24PRFDZWuFFk19AamHFpIHJz71FycZh4=
      - BROADCAST_DRIVER=reverb
      - REVERB_APP_ID=125566
      - REVERB_APP_KEY=1whzuivwq9cqn1dn4ilm
      - REVERB_APP_SECRET=yqix2nlsdvsw2csienwo
      - REVERB_HOST=reverb
      - REVERB_PORT=8000
      - REVERB_SCHEME=http
    depends_on:
      - reverb
    networks:
      - laravel

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_reverb
    command: ["php", "/var/www/artisan", "reverb:start", "--port=8000"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
