name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        IMAGE_TAG=$(date +%s)  # Unique tag based on current timestamp
        docker build . --file Dockerfile --tag koepido/bm-service-server:$IMAGE_TAG
        docker tag koepido/bm-service-server:$IMAGE_TAG koepido/bm-service-server:latest
        docker push koepido/bm-service-server:$IMAGE_TAG
        docker push koepido/bm-service-server:latest

do I need to make it here or in docker file

ChatGPT said:
